name: prepare

on:
  workflow_dispatch:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Expect
        run: sudo apt-get install -y expect
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build executable
        run: go build -o msh .

      - name: Run expect tests
        run: ./test.expect
